dependencies:
  - python=3.8.5
  - pip=23.1.2  # 更新 pip 到最新版本
  - setuptools>=60.0.0  # 确保 setuptools 是最新版本
  - cudatoolkit=11.0
  - pytorch=1.7.0
  - torchvision=0.8.1
  - numpy=1.19.2
  - pip:
    - albumentations==0.4.3
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.3.1
    - taming-transformers
    - packaging==21.3
    - torchmetrics<0.8
    - taming-transformers-rom1504
    - axial_positional_embedding
    - linear_attention_transformer
    - zhconv
    - -e .  # 安装当前目录下的包
