name: DiffTSR
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8.5
  - pip=23.1.2
  - cudatoolkit=11.0
  - pytorch=1.7.0=py3.8_cuda11.0.221_cudnn8.0.5_0
  - torchvision=0.8.1=py38_cu110
  - numpy=1.19.2
  - setuptools>=60.0.0
  - pip:
    - albumentations==0.4.3
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.3.1
    - taming-transformers
    - packaging==21.3
    - torchmetrics<0.8
    - taming-transformers-rom1504
    - axial_positional_embedding
    - linear_attention_transformer
    - zhconv
    - -e .  # 使用 pip 安装当前项目
