name: Run DiffTSR Inference

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-difftsr:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.8.5"
          activate-environment: DiffTSR
          environment-file: environment.yaml

      # 3. 激活 Conda 环境
      - name: Activate Conda environment
        shell: bash -l {0}
        run: |
          conda activate DiffTSR
          conda info

      # 4. 更新 pip 和 setuptools
      - name: Update pip and setuptools
        run: |
          python -m pip install --upgrade pip setuptools

      # 5. 安装本地包
      - name: Install package
        run: |
         pip install beautifulsoup4 argparse pillow
          pip install -e .

      # 6. 下载模型文件
      - name: Download models
        run: |
          python drive.arg.py --url https://drive.google.com/drive/folders/1K6k5ZcvF3w-1MDN_gXQTdsLgFZ2SM8qy?usp=drive_link
          ls -lh DiffTSR.ckpt transocr.pth

      # 7. 移动模型文件到指定路径
      - name: Move models to target directory
        run: |
          mkdir -p ./testset/0_lr_synth/
          mv DiffTSR.ckpt ./testset/0_lr_synth/
          mv transocr.pth ./testset/0_lr_synth/
          ls -lh ./testset/0_lr_synth/

      # 8. 运行 inference_DiffTSR.py
      - name: Run inference
        run: |
          python inference_DiffTSR.py

      # 9. 上传生成的超分辨率图片为 Artifacts
      - name: Upload SR images as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sr-images
          path: ./testset/0_sr_synth/
